=== egovernments/releasekit/mdms/Studio/V0.5/schemas/Studio.AppScreenLocalisationConfig.json
{
                "type": "object",
                "title": "Generated schema for Root",
                "$schema": "http://json-schema.org/draft-07/schema#",
                "required": [
                    "screenName",
                    "LocalisationModule",
                    "moduleVersion",
                    "minModuleVersion",
                    "fields"
                ],
                "x-unique": [
                    "screenName"
                ],
                "properties": {
                    "fields": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "fieldType"
                            ],
                            "properties": {
                                "fieldType": {
                                    "type": "string"
                                },
                                "applicableFieldTypes": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "localisableProperties": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    },
                    "screenName": {
                        "type": "string"
                    },
                    "moduleVersion": {
                        "type": "string"
                    },
                    "minModuleVersion": {
                        "type": "string"
                    },
                    "LocalisationModule": {
                        "type": "string"
                    }
                }
            }

=== egovernments/releasekit/mdms/Studio/SchemasData/Studio.AppScreenLocalisationConfigdata.json
[
    {
        "fields": [
            {
                "fieldType": "idPopulator",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "button",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "toggle",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "filter",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "searchBar",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "searchByProximity",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "BeneficiaryRegistrationButton",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "qrscanner",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "text",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "textInput",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "dropdown",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "dropdownOptions",
                    "dropDownOptions",
                    "message"
                ]
            },
            {
                "fieldType": "number",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "numeric",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "checkbox",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "numeric",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "scanner",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "date",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "dob",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "administrativeArea",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "latLng",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "textArea",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "mobileNumber",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "radio",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "select",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "editHousehold",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "editIndividual",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "Table",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "DetailsCard",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "addMember",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "IndividualDeliveryPrimaryButton",
                "localisableProperties": [
                    "errorMessage",
                    "tooltip",
                    "innerLabel",
                    "helpText",
                    "label",
                    "message"
                ]
            },
            {
                "fieldType": "IndividualDeliverySecondaryButton",
                "localisableProperties": [
