=== egovernments/releasekit/mdms/Studio/schemas/common-masters.Department.json
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "required": [
        "code"
    ],
    "x-unique": [
        "code"
    ],
    "properties": {
        "id": {
            "type": "number"
        },
        "code": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "active": {
            "type": "boolean"
        },
        "tenantId": {
            "type": "string"
        }
    }
}

=== egovernments/releasekit/mdms/Studio/SchemasData/common-masters.Departmentdata.json
[
    {
        "id": 1,
        "code": "NMCP",
        "name": "NMCP",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 2,
        "code": "DHI",
        "name": "DHI",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 3,
        "code": "DICT",
        "name": "DICT",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 4,
        "code": "SPS",
        "name": "SPS",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 15,
        "code": "TEST",
        "name": "TEFST",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 5,
        "code": "DPS",
        "name": "DPS",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 6,
        "code": "Visao Mundial",
        "name": "Visao Mundial",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 7,
        "code": "ADPP",
        "name": "ADPP",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 8,
        "code": "FDC",
        "name": "FDC",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 9,
        "code": "FH",
        "name": "FH",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 10,
        "code": "CHAI",
        "name": "CHAI",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 11,
        "code": "eGov",
        "name": "eGov",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 12,
        "code": "MISAU",
        "name": "MISAU",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 13,
        "code": "OTHER",
        "name": "OTHER",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 14,
        "code": "MALARIA",
        "name": "MALARIA",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 2,
        "code": "TECH",
        "name": "TECH",
        "active": true,
        "tenantId": "st"
    },
    {
        "id": 3,
        "code": "WAREHOUSE",
        "name": "WAREHOUSE",
        "active": true,
        "tenantId": "st"
    }
]
