=== egovernments/releasekit/mdms/Studio/schemas/common-masters.Designation.json
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "required": [
        "code"
    ],
    "x-unique": [
        "code"
    ],
    "properties": {
        "code": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "active": {
            "type": "boolean"
        },
        "description": {
            "type": "string"
        }
    }
}

=== egovernments/releasekit/mdms/HCM/Studio/SchemasData/common-masters.Designationdata.json
[
    {
        "code": "DESIG_06",
        "name": "Superintending Engineer ( O&M)",
        "active": true,
        "description": "Superintending Engineer ( O&M)"
    },
    {
        "code": "DESIG_01",
        "name": "Superintending Engineer ( B&R)",
        "active": true,
        "description": "Superintending Engineer ( B&R)"
    },
    {
        "code": "DESIG_02",
        "name": "Corporation Engineer (B&R)",
        "active": true,
        "description": "Corporation Engineer (B&R)"
    },
    {
        "code": "DESIG_03",
        "name": "Asst. Engineer ( B&R)",
        "active": true,
        "description": "Asst. Engineer ( B&R)"
    },
    {
        "code": "DESIG_04",
        "name": "Junior Engineer ( B&R)",
        "active": true,
        "description": "Junior Engineer ( B&R)"
    },
    {
        "code": "DESIG_05",
        "name": "Land Scape Officer",
        "active": true,
        "description": "Land Scape Officer"
    },
    {
        "code": "DESIG_07",
        "name": "Corporation Engineer (O&M)",
        "active": true,
        "description": "Corporation Engineer (O&M)"
    },
    {
        "code": "DESIG_08",
        "name": "Asst. Engineer ( O&M)",
        "active": true,
        "description": "Asst. Engineer ( O&M)"
    },
    {
        "code": "DESIG_09",
        "name": "Junior Engineer ( O&M)",
        "active": true,
        "description": "Junior Engineer ( O&M)"
    },
    {
        "code": "DESIG_10",
        "name": "Superintending Engineer ( Light)",
        "active": true,
        "description": "Superintending Engineer ( Light)"
    },
    {
        "code": "DESIG_11",
        "name": "Corporation Engineer (Light)",
        "active": true,
        "description": "Corporation Engineer (Light)"
    },
    {
        "code": "DESIG_12",
        "name": "Junior Engineer ( Light)",
        "active": true,
        "description": "Junior Engineer ( Light)"
    },
    {
        "code": "DESIG_13",
        "name": "Health Officer",
        "active": true,
        "description": "Health Officer"
    },
    {
        "code": "DESIG_14",
        "name": "Medical Officer",
        "active": true,
        "description": "Medical Officer"
    },
    {
        "code": "DESIG_15",
        "name": "Chief Sanitary Inspector",
        "active": true,
        "description": "Mechanical Oversear"
    },
    {
        "code": "DESIG_16",
        "name": "Sainitary Inspector",
        "active": true,
        "description": "Clerk"
    },
    {
        "code": "DESIG_17",
        "name": "Sainitary Supervisor",
        "active": true,
        "description": "Accountant"
    },
    {
        "code": "DESIG_18",
        "name": "Senior Town Planner",
        "active": true,
        "description": "Senior Town Planner"
    },
    {
        "code": "DESIG_19",
        "name": "Municipal Town Planner",
        "active": true,
        "description": "Municipal Town Planner"
    },
    {
        "code": "DESIG_20",
        "name": "Asst. Town Planner",
        "active": true,
        "description": "Asst. Town Planner"
    },
    {
        "code": "DESIG_21",
        "name": "Building Inspector",
        "active": true,
        "description": "Building Inspector"
    },
    {
        "code": "DESIG_22",
        "name": "Junior Enginer ( Horticulutre)",
        "active": true,
        "description": "Junior Enginer ( Horticulutre)"
    },
    {
        "code": "DESIG_23",
        "name": "Citizen service representative",
        "active": true,
        "description": "Citizen service representative"
    },
    {
        "code": "DESIG_1001",
        "name": "Deputy Controller Finance and Accounts",
        "active": true,
        "description": "Deputy Controller Finance and Accounts"
    },
    {
        "code": "DESIG_58",
        "name": "Accountant",
        "active": true,
        "description": "Accountant"
    },
    {
        "code": "DESIG_24",
        "name": "Assistant Commissioner",
        "active": true,
        "description": "Assistant Commissioner"
    },
    {
        "code": "DESIG_47",
        "name": "Superintendent",
        "active": true,
        "description": "Superintendent"
    },
    {
        "code": "DESIG_59",
        "name": "Accounts Officer",
        "active": true,
        "description": "Accounts Officer"
    },
    {
        "code": "DESIG_60",
        "name": "Commissioner",
        "active": true,
        "description": "Commissioner"
    }
]
